# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def migrate_data(apps, schema_editor):
    Client = apps.get_model('address_book', 'Client')
    NewAddress = apps.get_model('address_book', 'NewAddress')

    for c in Client.objects.all():
        for a in c.addresses.all():
            NewAddress.objects.create(street_name=a.street_name, client=c)

class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Client')),
            ],
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop)
    ]
