# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_newaddress_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='addresses',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
