# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bought',
            field=models.IntegerField(null=True),
        ),
    ]
