# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations


def add_bought(apps, schema_editor):
    Client = apps.get_model('store', 'Client')
    for c in Client.objects.all():
        c.bought = c.computers.count()
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_client_bought'),
    ]

    operations = [
        migrations.RunPython(add_bought, reverse_code=migrations.RunPython.noop)
    ]
